import "server-only";
import { isSameCompany } from "@/lib/privacy/normalizer";
import { HAIKU } from "@/lib/ai";
import { callClaudeForJson } from "@/lib/ai/json-call";
import {
  buildPositioningClassificationPrompt,
  type PositioningClassificationContext,
} from "@/lib/ai/positioning-prompts";
import { PositioningClassificationSchema } from "@/lib/types/schemas";
import type {
  CompanyProfile,
  ParsedResume,
  PositioningClassification,
  PositioningType,
  RoleType,
} from "@/types";

// ─── Section 4 — Classification signal order ─────────────────────────────
//
// Two signals, strict order. Deterministic match short-circuits before
// any Claude call.
//
//   1. PRIMARY  — CompanyProfile.competitors (auto-generated by
//                 /api/company-research). Fuzzy-match each past employer.
//                 Match → direct_competitor at confidence 0.85, signal
//                 company_profile_competitors.
//   2. FALLBACK — Claude Haiku, full 6-type prompt. This is where
//                 adjacent_player, ecosystem, category_switcher,
//                 industry_switcher, and early_career get decided.
//                 Signal: haiku_classification.
//
// NOTE (drift): an earlier draft of this engine spec'd a curated
// `competitors` column on the live company_interview_intel table as
// Signal 1. The live DB's company_interview_intel turned out to be a
// completely different (stage-keyed) table than what the repo's
// migrations describe — the curated column couldn't be added without a
// broader DB reconciliation, so Signal 1 was dropped. Promoting Signal 2
// to primary preserves the deterministic-short-circuit path without
// requiring an admin-curated override layer the live schema doesn't
// support.
//
// Priority across multiple past employers: ANY matched past employer
// flips the session to direct_competitor — per Section 3's "if ANY past
// employer is a direct competitor" rule. For non-deterministic paths,
// the Haiku prompt enforces:
//   direct_competitor > ecosystem > adjacent_player
//   > category_switcher > industry_switcher > early_career
//
// This function NEVER throws. On Haiku/Zod failure it returns a safe
// default rather than blocking session creation.
// ─────────────────────────────────────────────────────────────────────────

/**
 * Fuzzy-match a past employer against a competitor list using the
 * shared normalizer (handles "Inc.", "LLC", ".com", aliases like
 * "SFDC" → "salesforce").
 */
function findMatch(
  pastEmployers: { company: string; title: string }[],
  competitorList: string[]
): { employer: string; role: string } | null {
  for (const employer of pastEmployers) {
    if (!employer.company) continue;
    for (const competitor of competitorList) {
      if (isSameCompany(employer.company, competitor)) {
        return { employer: employer.company, role: employer.title };
      }
    }
  }
  return null;
}

function pastEmployersFromResume(resume: ParsedResume): { company: string; title: string }[] {
  return (resume.roles ?? [])
    .filter((r) => r.company && r.company.trim().length > 0)
    .map((r) => ({ company: r.company, title: r.title ?? "" }));
}

function buildEmploymentHistoryBlock(resume: ParsedResume): string {
  const employers = resume.roles ?? [];
  if (employers.length === 0) {
    return "(no professional employment history on resume)";
  }
  return employers
    .map((r) => {
      const range = `${r.startDate ?? "?"}–${r.endDate ?? "present"}`;
      const months = r.durationMonths != null ? ` (~${r.durationMonths}mo)` : "";
      return `- ${r.title ?? "Unknown role"} at ${r.company ?? "Unknown employer"} (${range})${months}`;
    })
    .join("\n");
}

function buildCompanySummaryBlock(company: CompanyProfile): string {
  return [
    `Name: ${company.name}`,
    `Product: ${company.productDescription}`,
    `Sales motion: ${company.salesMotion}`,
    `Stage: ${company.stage}`,
    `ICP industries: ${(company.icp?.industries ?? []).join(", ") || "unknown"}`,
    `Buyer personas: ${(company.icp?.buyerPersonas ?? []).join(", ") || "unknown"}`,
    `Auto-detected competitors: ${(company.competitors ?? []).join(", ") || "unknown"}`,
  ].join("\n");
}

/**
 * Safe-default classification when Haiku/Zod fail. Picks the floor
 * consistent with what the resume actually shows — never invents an
 * anchor employer or a competitive relationship.
 */
function safeDefault(
  resume: ParsedResume,
  reason: string
): PositioningClassification {
  // Map backgroundType to the safest floor that doesn't overclaim.
  let positioning_type: PositioningType;
  switch (resume.backgroundType) {
    case "experienced_sales":
      positioning_type = "category_switcher";
      break;
    case "career_switcher":
    case "other":
      positioning_type = "industry_switcher";
      break;
    case "new_grad":
    default:
      positioning_type = "early_career";
      break;
  }

  return {
    positioning_type,
    anchor_employer: null,
    anchor_employer_role: null,
    classification_reasoning: `Safe default applied — ${reason}. Floor chosen from resume.backgroundType=${resume.backgroundType}.`,
    classification_confidence: 0.3,
    classification_signal: "haiku_classification",
  };
}

export async function classifyPositioning(
  resume: ParsedResume,
  company: CompanyProfile,
  roleType: RoleType
): Promise<PositioningClassification> {
  const pastEmployers = pastEmployersFromResume(resume);

  // ── Signal 1: CompanyProfile.competitors (auto-generated) ──
  if (pastEmployers.length > 0) {
    const autoCompetitors = company.competitors ?? [];
    if (autoCompetitors.length > 0) {
      const match = findMatch(pastEmployers, autoCompetitors);
      if (match) {
        return {
          positioning_type: "direct_competitor",
          anchor_employer: match.employer,
          anchor_employer_role: match.role || null,
          classification_reasoning: `Matched ${match.employer} against the auto-generated competitor list on the company profile for ${company.name}.`,
          classification_confidence: 0.85,
          classification_signal: "company_profile_competitors",
        };
      }
    }
  }

  // ── Signal 2: Claude Haiku fallback (6-type classification) ──
  const promptCtx: PositioningClassificationContext = {
    employmentHistory: buildEmploymentHistoryBlock(resume),
    companySummary: buildCompanySummaryBlock(company),
    interviewIntelSummary: "",
    roleType,
  };
  const { system, user, maxTokens } = buildPositioningClassificationPrompt(promptCtx);

  try {
    const { data } = await callClaudeForJson({
      model: HAIKU,
      system,
      user,
      maxTokens,
      schema: PositioningClassificationSchema,
      label: "classifyPositioning",
    });

    // The model is instructed to always emit 'haiku_classification' for
    // this signal; harden against drift just in case.
    return { ...data, classification_signal: "haiku_classification" };
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    return safeDefault(resume, `Haiku classification failed: ${reason}`);
  }
}
