-- Seed 39 additional companies from definitive SDR interview guide.
-- Covers infrastructure/security, developer tools, marketing tech, enterprise giants, and high-growth tiers.
-- Source: Glassdoor reviews, RepVue scores, Bravado community reports, and hiring manager interviews.

INSERT INTO company_interview_intel (
  company_name, company_name_normalized, interview_rounds, avg_days_to_hire,
  key_test, unique_element, mock_call_format,
  common_questions, red_flags, tips, sdr_satisfaction_score
) VALUES

-- ── Infrastructure & Security Tier ──────────────────────────────────────────

('Stripe', 'stripe', 4, 17,
 'Mock cold call + 2-part written take-home project (3 business days)',
 'Process is notably candidate-friendly — they offer feedback calls even after rejection. The written take-home carries heavy weight and tests strategic thinking, not just phone presence.',
 'Standard mock cold call + written take-home project',
 ARRAY['Why sales? Why Stripe?', 'Prioritization exercises', 'Walk me through your prospecting approach', 'How would you research and approach a fintech company?'],
 ARRAY['Failing to articulate clear reasons for wanting to work in payments/fintech', 'Rushing the written take-home project', 'Not understanding Stripes developer-first sales motion'],
 ARRAY['Allocate significant time for the written project — it carries heavy weight', 'Stripe gives feedback calls even after rejection — rare and valuable', '74% of SDRs hit quota — strong attainment', 'OTE $75K-$95K with 64/36 base/variable split'],
 3.8),

('MongoDB', 'mongodb', 5, 18,
 '90-minute SDR Challenge: account strategy PowerPoint + role play + operational strategy — all in one session',
 'Most comprehensive single assessment in any SDR interview. Company offers a 30-minute prep call with the hiring manager beforehand — take it.',
 'Role play embedded within the 90-minute SDR Challenge',
 ARRAY['Territory management questions', 'Why NoSQL?', 'Present your account strategy', 'How would you prioritize accounts in a new territory?'],
 ARRAY['Weak presentation skills', 'No understanding of MongoDB vs SQL databases', 'Poor operational strategy answers'],
 ARRAY['The 30-minute prep call with the hiring manager is invaluable — always accept it', '75% positive interview experience — highest among infrastructure companies', 'Bootcamp onboarding in New York is considered best-in-class', 'Base salary is lowest in tier ($47.5K-$52.5K) but training is exceptional'],
 4.2),

('Cloudflare', 'cloudflare', 5, 33,
 '20-minute role play + executive final interview (sometimes CEO Matthew Prince)',
 'Longest process in infrastructure tier at 33 days. Up to 10 individual interviewers including executive/CEO. Their philosophy: You can never overprepare but you can definitely underprepare.',
 '20-minute structured role play',
 ARRAY['How would you describe Cloudflare to your grandmother?', 'What is a DDoS attack?', 'Why Cloudflare?', 'Technical questions about web security basics'],
 ARRAY['Asking salary questions to non-recruiters', 'Not knowing basic web security concepts', 'Underpreparing — they test depth across 10 interviewers'],
 ARRAY['Prepare the grandmother test answer for Cloudflare — they literally ask this', 'Know basic cybersecurity terms: DDoS, CDN, DNS, WAF', 'Career progression for BDRs is a known weakness (2.8/5) — ask about it strategically', 'Culture & Leadership rated only 2.7/5 — go in with eyes open'],
 3.0),

('Palo Alto Networks', 'palo alto networks', 3, 25,
 'Role play with a panel of sales managers',
 'Simplest process in infrastructure tier — just 3 rounds. Interview difficulty rated only 2.8/5, the easiest among infrastructure companies.',
 'Panel role play with multiple sales managers',
 ARRAY['What was one hardship you faced and how did you navigate that?', 'Tell me about your cold calling experience', 'Why cybersecurity?', 'How do you handle rejection?'],
 ARRAY['Insufficient cold calling experience — specifically cited as rejection reason', 'Not knowing the competitive landscape (CrowdStrike, Fortinet)', 'Low energy in the panel'],
 ARRAY['Commissions are capped — know this going in and dont let it surprise you', 'Know CrowdStrike and Fortinet competitive positioning cold', 'RepVue score 85.81 — strong overall', 'Product-Market Fit rated 4.4/5'],
 4.3),

('ServiceNow', 'servicenow', 4, 22,
 'Behavioral only — no standardized mock call or take-home for SDRs',
 'Highest RepVue score in infrastructure tier (87.92). Most base-heavy pay structure at 72/28 split. Relies entirely on behavioral interviews.',
 NULL,
 ARRAY['What does success look like to you?', 'Tell me about a time you handled competing priorities', 'Why ServiceNow?', 'How do you build relationships with multiple stakeholders?'],
 ARRAY['Answers that sound too rehearsed — a candidate was specifically rejected for this', 'Not understanding the LDR to SDR to AE promotion path', 'Generic answers without specific examples'],
 ARRAY['No mock call or take-home — prepare strong STAR stories instead', 'SDRs support 5-6 field reps and make ~35 calls and 45 emails daily', 'Promotion path: LDR → SDR → AE with 12-18 month timelines', 'Highest RepVue score (87.92) and highest base proportion (72/28)'],
 4.4),

-- ── Developer Tools & Security Tier ─────────────────────────────────────────

('Twilio', 'twilio', 4, 25,
 'Twilio Magic values assessment + Bar Raiser interview (cross-team senior leader evaluator)',
 'Bar Raiser system borrowed from Amazon — a senior leader from outside the hiring team evaluates independently. Every question maps to Twilio Magic principles. Offers arrive within 48 hours; 6-month cooling period if rejected.',
 'Values-based behavioral — no standard mock call',
 ARRAY['Describe a time you dealt with a difficult stakeholder', 'How do you embody Draw the Owl?', 'Tell me about Twilio Magic', 'Give an example of Empowering Others'],
 ARRAY['Not demonstrating alignment with Twilio Magic values', 'Not knowing the 4 principles: Draw the Owl, Empower Others, Be Inclusive, No Shenanigans', 'Failing the Bar Raiser evaluation'],
 ARRAY['Memorize Twilio Magic: Draw the Owl, Empower Others, Be Inclusive, No Shenanigans', 'The Bar Raiser is from outside the team — they evaluate independently', 'Offers arrive within 48 hours of final interview', '6-month cooling period if rejected — make it count'],
 4.2),

('Okta', 'okta', 3, 19,
 'Mock cold call — the make-or-break final round',
 'Fastest and leanest process at just 3 rounds and 19 days. The mock cold call is the primary gating mechanism.',
 'Mock cold call pitching Okta identity security product with limited prep time',
 ARRAY['Walk me through how youd cold call a CISO about identity security', 'Why Okta?', 'Mock cold call (final round)', 'How do you handle technical objections?'],
 ARRAY['Low energy', 'Not understanding identity security basics', 'Poor mock call performance — its the primary filter'],
 ARRAY['Only 3 rounds and 19 days — fastest process in tier', 'Reviews are sharply divided on culture — research thoroughly', 'Recent shift to 5 days in-office is a major change', 'Only 41% quota attainment is concerning — ask about it'],
 3.2),

('Splunk', 'splunk', 4, 23,
 'Cold call example + 30/60/90 day plan',
 'Highest BDR satisfaction rating at 4.6/5 on Glassdoor with 4.7/5 work-life balance. Now part of Cisco — process may route through Cisco hiring systems.',
 'Cold call demonstration + ramp plan presentation',
 ARRAY['Walk me through a cold call example', 'Present your 30/60/90 day plan', 'Why observability and data analytics?', 'How would you ramp in a new territory?'],
 ARRAY['Not having a prepared 30/60/90 day plan', 'Not taking the free Splunk Fundamentals 1 course', 'Not knowing Splunk was acquired by Cisco'],
 ARRAY['Take the free Splunk Fundamentals 1 eLearning course before interviewing — gives a significant edge', 'Arrive with a prepared 30/60/90 day ramp plan', 'BDR org reports to Marketing not Sales — understand this structure', 'Highest BDR Glassdoor rating at 4.6/5'],
 4.6),

('Confluent', 'confluent', 5, 26,
 'Extensive take-home (~7 hours): territory plan, 10 target accounts, prospecting email, 6-month plan + mock customer call',
 'Most time-intensive take-home in any SDR interview at ~7 hours. Must answer: Why should a customer buy Confluent Cloud when Apache Kafka is free?',
 'Mock customer call as part of the take-home presentation',
 ARRAY['Why should a customer buy Confluent Cloud when Apache Kafka is free?', 'Present your territory plan and 10 target accounts', 'Walk me through your prospecting email strategy', 'Mock customer call'],
 ARRAY['Generic email in the take-home', 'Not understanding why paid Confluent beats free Kafka', 'Weak target account justification'],
 ARRAY['The take-home takes ~7 hours — allocate a full day', 'The core question is why pay for Confluent when Kafka is free — nail this', 'You present to a panel for 1.5 hours of questions', 'WARNING: 2024 report says No SDRs as of 2024 — verify SDR function exists before applying'],
 3.2),

('HashiCorp', 'hashicorp', 4, 25,
 'Principles-based behavioral interview built around 9 core principles',
 'Entire interview built around 9 principles: integrity, kindness, pragmatism, humility, etc. Process described as radically transparent. Now part of IBM — significant culture changes.',
 NULL,
 ARRAY['How do you demonstrate integrity in your work?', 'Give an example of pragmatism over perfection', 'Why HashiCorp?', 'How do you approach learning complex technical products?'],
 ARRAY['Not knowing the 9 core principles', 'Not addressing IBM acquisition changes', 'Generic answers that dont map to specific principles'],
 ARRAY['Learn all 9 core principles and prepare STAR stories for each', 'Interviewers share what theyre evaluating — radically transparent process', '$70K base is highest in tier', 'IBM acquisition has created turmoil — ask about current culture carefully'],
 3.5),

-- ── Product & Growth Tier ───────────────────────────────────────────────────

('Elastic', 'elastic', 4, 14,
 'No formal test — behavioral/qualitative interviews focused on motivation and curiosity',
 'Explicitly values quality of interactions over quantity of calls — a rarity in SDR orgs. No mock call or take-home. 14-day process is fastest in tier.',
 NULL,
 ARRAY['Tell me about a time you balanced lots of responsibilities', 'What makes you curious about technology?', 'Why Elastic?', 'How do you approach research before outreach?'],
 ARRAY['Lack of genuine curiosity about technology', 'Quantity-over-quality mindset', 'Not understanding Elastics search and observability platform'],
 ARRAY['No mock call or take-home — focus entirely on behavioral STAR stories', 'Quality over quantity is their philosophy — demonstrate this', '68% quota attainment is strong, but quotas increasing ~30% QoQ', 'Candidates praise the recruiter experience as the best theyve ever had'],
 4.2),

('Atlassian', 'atlassian', 5, 17,
 'Mock cold call + dedicated values interview conducted by anyone in the company',
 'Dedicated values interview round can be conducted by Marketing, Engineering, or any department — heavily weighted. Enterprise Dev Rep pays $93K-$105K OTE.',
 'Mock cold call + values interview round',
 ARRAY['Tell me about a time you demonstrated Open Company No Bullshit', 'STAR stories for each of Atlassians 5 values', 'Mock cold call', 'Why Atlassian?'],
 ARRAY['Not knowing Atlassians 5 values', 'Not having STAR stories mapped to each value', 'Treating the values interview as less important than the mock call'],
 ARRAY['Prepare STAR stories for each of Atlassians 5 values including Open Company No Bullshit', 'The values interview can come from ANY department — its heavily weighted', 'Top performers earn $150K-$200K', 'Glassdoor warns of unrealistic expectations and 30% quota increases QoQ'],
 3.8),

('Monday.com', 'monday', 6, 21,
 '3-page take-home questionnaire + mock cold call + on-the-spot email writing',
 'Most criticized process: 3-page take-home requiring 5 contacts at a sample company, entire outreach cadence, 2 prospecting emails, and 4 sales scenario responses — all for entry-level. Multiple reviews call it hours of free labor.',
 'Mock cold call + on-the-spot email creation',
 ARRAY['Find 5 contacts at this sample company', 'Create an outreach cadence', 'Draft 2 prospecting emails', 'Write responses to 4 sales scenarios', 'Mock cold call'],
 ARRAY['Rushing the take-home — its extensive', 'Generic outreach cadence', 'Poor on-the-spot email writing'],
 ARRAY['SDR comp satisfaction at 2.6/5 is lowest across all 40 companies', 'The take-home is extensive — allocate several hours', '67% of SDRs hit quota despite low comp satisfaction', 'Process widely criticized as excessive for entry-level — factor this into your decision'],
 2.8),

('Figma', 'figma', 5, 25,
 'Mock discovery call/role play',
 'Exceptional product-market fit (4.7/5, ranked #125 out of 2,994 companies on RepVue). Pre-IPO equity makes total comp significant. Getting a referral is reportedly critical.',
 'Mock discovery call role play',
 ARRAY['Tell me about a deal that slipped', 'Why Figma?', 'Mock discovery call', 'How would you sell a design tool to engineering leaders?'],
 ARRAY['Asking too many questions during a sales scenario — one candidate was rejected for this', 'Not having a referral — its hard to get into the process otherwise', 'Not understanding the design-to-development workflow'],
 ARRAY['Getting a referral is critical — its hard to get in otherwise', 'Product-Market Fit 4.7/5 — one of the strongest in tech', 'Pre-IPO equity adds significant upside to ~$110K OTE', 'BDR segment is growing fast with clear AE promotion path'],
 4.2),

('Amplitude', 'amplitude', 4, 45,
 'Behavioral interviews focused on Fortune 500 prospecting',
 'Most concerning SDR culture in the guide. Reviews describe extreme micromanagement, activity tracked and watched daily, passive aggressive managers, and culture of gossip about whos on the chopping block.',
 NULL,
 ARRAY['How would you prospect into a Fortune 500 company?', 'Tell me about your approach to complex sales cycles', 'Why digital analytics?', 'How do you handle long sales cycles?'],
 ARRAY['Inability to pitch complex analytics to enterprise buyers', 'Not being prepared for micromanagement culture', 'Expecting quick promotion — takes 2+ years'],
 ARRAY['Product is incredibly hard to pitch in a quick email — practice extensively', 'Training reportedly run by someone who has no idea what the SDR role actually is', 'Takes 2+ years to get promoted', 'If you thrive in high-accountability environments the product and comp are strong — but go in with eyes open'],
 2.5),

-- ── Marketing Tech & Vertical Tier ──────────────────────────────────────────

('Braze', 'braze', 4, 23,
 '48-hour BDR email challenge (take-home prospecting exercise)',
 'Most aggressive base-to-variable split at 53/47 — variable pay is nearly half of total comp. Only 39% of reps meet quota, so that split carries real risk.',
 NULL,
 ARRAY['What data did you use to influence a campaign?', 'Draft prospecting emails under 48-hour deadline', 'Why customer engagement platforms?', 'How do you personalize outreach at scale?'],
 ARRAY['Generic prospecting emails in the challenge', 'Not understanding customer engagement vs traditional marketing', 'Not accounting for the aggressive variable split'],
 ARRAY['The 48-hour email challenge is the core differentiator — invest real time', '53/47 base/variable split is most aggressive in the industry', 'Only 39% meet quota — ask about quota methodology', 'No brilliant jerks philosophy — culture matters here'],
 3.6),

('Toast', 'toast', 4, 25,
 'Mock cold call on a restaurant + sales pitch preparation',
 'Industry-specific mock call: you role-play calling a restaurant about switching POS systems. Company provides a Sandler Sales PDF to review. Managers give coaching feedback after the mock call.',
 'Restaurant-specific cold call role play + Sandler methodology',
 ARRAY['Mock cold call to a restaurant owner', 'Why restaurant technology?', 'How would you pitch switching POS systems?', 'Tell me about a time you handled multiple priorities'],
 ARRAY['Not knowing the restaurant industry pain points', 'Not reviewing the Sandler Sales PDF they provide', 'Not implementing coaching feedback after the mock call'],
 ARRAY['Review the Sandler Sales PDF they provide before the interview', 'The mock call is restaurant-specific — research restaurant POS pain points', 'Managers give coaching feedback after mock call — implement it visibly', 'RepVue 87.20 is strong. PTO requests can be rejected if not hitting quota'],
 4.3),

('Klaviyo', 'klaviyo', 4, 23,
 'Mock cold call + prospecting email — NO provided value props or scripts',
 'Notably harder mock call than competitors because you receive no canned value props. Must independently research Klaviyos product, target persona, and prospect company. Requires 2-5 hours of prep.',
 'Unscripted mock cold call — no value props provided, must self-research',
 ARRAY['Tell me about a deal where you fell short and why', 'Mock cold call (unscripted)', 'Prospecting email draft', 'Why email marketing and customer data?'],
 ARRAY['Relying on provided scripts — there are none', 'Not spending 2-5 hours researching before the mock call', 'Generic prospecting approach'],
 ARRAY['You get NO canned value props — independently research Klaviyos product, persona, and prospect', 'Mock call requires 2-5 hours of prep minimum', 'No brilliant jerks policy from CEO Andrew Bialecki', 'Recruiter communication is inconsistent — follow up proactively'],
 3.5),

('Deel', 'deel', 4, 18,
 'Mock discovery call + take-home test + video recordings',
 'Deel Speed is a core value — process often concludes in under 2 weeks. 89% of SDRs recommend Deel. Some positions are contractor roles without traditional benefits — ask upfront.',
 'Mock discovery call + take-home + 2 video recordings + prospecting exercise',
 ARRAY['Mock discovery call for company called Rocket Labs', 'Take-home test', 'Video recording submissions', 'Why global payroll and HR?'],
 ARRAY['Not matching Deel Speed pace', 'Not asking whether the role is employee or contractor', 'Slow response times during the process'],
 ARRAY['Process moves fast — Deel Speed is a core value, respond quickly', '89% of SDRs recommend Deel with 4.4/5 satisfaction', 'Some positions are contractor roles — ask upfront about employment status', 'Fully remote model is a draw but research recent espionage controversy'],
 4.4),

('Rippling', 'rippling', 4, 22,
 'Mock cold call with senior manager/director (final round)',
 'Strong pay and training but polarizing culture. 80 cold calls per day expected. Unofficial guidance: dont take PTO for first 4 months. Pre-IPO equity adds significant upside.',
 'Mock cold call with senior manager or director',
 ARRAY['Mock cold call', 'Why HR/IT platform?', 'How do you handle high-volume outbound?', 'Tell me about a time you pushed through adversity'],
 ARRAY['Not being prepared for 80 calls/day expectation', 'Outfit and directness — one candidate rejected because HM didnt like my outfit and my answers were too direct', 'Expecting work-life balance — WLB rated 2.6/5'],
 ARRAY['Enablement and training are second to none — managers described as incredible', 'This is high-risk high-reward: compress years of learning into months', 'Pre-IPO equity adds significant upside to $85K-$120K OTE', 'SDR reviews describe 12+ hour days — ideal for candidates who want intensity'],
 3.2),

-- ── Enterprise Giants ───────────────────────────────────────────────────────

('Oracle', 'oracle', 4, 21,
 'Elevator pitch in front of 20+ candidates + case study mock call + panel Q&A with current BDCs',
 'Group interview format — 20+ candidates on Zoom giving elevator pitches. Being first to ask a question during BDC panel reportedly matters. Only 5-10% promotion rate internally.',
 'Case study mock call + group elevator pitch',
 ARRAY['Elevator pitch (in front of 20+ candidates)', 'Case study mock call', 'Panel Q&A with current BDCs', 'Why Oracle?'],
 ARRAY['Asking about growth beyond BDR — was penalized in one report', 'Not standing out in the group setting', 'Not being first to ask questions during BDC panel'],
 ARRAY['Be first to ask a question during the BDC panel — it reportedly matters', 'Only 5-10% promote internally — most leave after 1-2 years for external roles', 'Oracle has been known to rescind offers', 'Group format with 20+ candidates is unusual — prepare to stand out quickly'],
 2.8),

('SAP', 'sap', 4, 21,
 'Role play phone calls + live SDR call shadowing',
 'Unique live call shadowing: candidates sit with current SDRs, listen to real calls, and ask questions between calls. Day in the life element helps both sides assess fit.',
 'Role play phone calls + live call shadowing with current SDRs',
 ARRAY['What is your experience with cold calling?', 'How many calls per week do you make?', 'Why enterprise software?', 'Questions during live call shadowing'],
 ARRAY['Not asking good questions during the call shadowing', 'No cold calling experience', 'Not understanding enterprise sales cycles'],
 ARRAY['The live call shadowing is unique — prepare thoughtful questions to ask between calls', 'Interview culture is friendly and relationship-focused', 'SAP Concur SDR teams are a strong launchpad', 'OTE $80K-$95K with 71/29 split — base-heavy'],
 3.8),

('Microsoft', 'microsoft', 5, 28,
 'Presentation/mock demo + cultural pillars assessment (Create Clarity, Generate Energy, Deliver Success)',
 'Highest SDR comp in the entire industry — $160K median OTE. Aspire Program is a 2-year rotational entry for new grads. Growth mindset is assessed throughout. Internal mobility is exceptional.',
 'Presentation/mock demo format',
 ARRAY['Demonstrate Create Clarity with a specific example', 'How do you Generate Energy in a team?', 'Tell me about delivering success under pressure', 'Show growth mindset'],
 ARRAY['Not knowing the 3 cultural pillars', 'Not demonstrating growth mindset', 'Treating it like a standard SDR interview — this is enterprise-scale'],
 ARRAY['Know the 3 pillars: Create Clarity, Generate Energy, Deliver Success', '$160K median OTE is #1 across all tech SDR roles', 'Aspire Program is a 2-year rotational entry for new grads', 'Entry-level Aspire SDRs earn less than median but still well above industry average'],
 4.5),

('Google Cloud', 'google cloud', 4, 28,
 'Structured behavioral interviews + Role-Related Knowledge (RRK) + Googleyness evaluation + hiring committee review',
 'Hiring committee model means the decision isnt made by the hiring manager alone — reduces individual bias. Googleyness evaluates intellectual curiosity, collaboration, and humility.',
 NULL,
 ARRAY['Describe a time you influenced someone without authority', 'What does Googleyness mean to you?', 'How do you approach learning a complex product?', 'Tell me about a time you collaborated across teams'],
 ARRAY['Not preparing 8-10 STAR stories mapped to Googles 4 assessment areas', 'Lacking intellectual curiosity', 'Not understanding the hiring committee process'],
 ARRAY['Prepare 8-10 STAR stories mapped to 4 areas: General Cognitive, Leadership, Role-Related Knowledge, Googleyness', 'The hiring committee reviews all feedback — not just the HMs opinion', 'Cost cuts since 2024 have affected morale — research current state', 'OTE $90K-$130K with 60/40 split'],
 4.1),

('AWS', 'aws', 5, 27,
 '16 Leadership Principles + STAR method + Bar Raiser interview with veto power — 4-5 back-to-back 1-hour interviews (The Loop)',
 'Most structured and demanding SDR interview. Every question maps to one of 16 Leadership Principles. The Loop is a mental marathon. Bar Raiser has veto power. 70% quota attainment is the best of any company.',
 NULL,
 ARRAY['Tell me about a time you demonstrated Customer Obsession', 'Describe when you showed Bias for Action', 'Give an example of Ownership', 'How have you earned trust?'],
 ARRAY['Using we instead of I — critical red flag', 'Vague answers without specific metrics', 'Hypothetical responses instead of real STAR examples', 'Not preparing for all 16 Leadership Principles'],
 ARRAY['Prepare 2-3 STAR stories for EACH of the 16 Leadership Principles', 'The Bar Raiser has veto power over any hire', 'The Loop is 4-5 consecutive hour-long interviews — pace yourself mentally', '70% quota attainment is best in industry. $145K median OTE is among highest'],
 4.2),

('IBM', 'ibm', 3, 30,
 'Resume deep-dive + case question (even for sales roles)',
 'Simplest process among enterprise companies — just 2-3 rounds. Uses Digital Sales Specialist titles. Surprisingly strong compensation at $125K median OTE with $85K base.',
 NULL,
 ARRAY['Walk me through your resume in detail', 'Case question about a sales scenario', 'Why IBM?', 'How would you approach selling AI/watsonx solutions?'],
 ARRAY['Not being able to walk through resume in granular detail', 'Not understanding IBMs AI/watsonx narrative', 'Not being prepared for case-study format'],
 ARRAY['Simplest enterprise process — just 2-3 rounds', '$125K median OTE with $85K base is surprisingly strong', 'AI/watsonx initiatives provide a compelling product narrative', 'Some describe culture as sales sweatshop with unrealistic quotas — ask direct questions'],
 3.5),

('Cisco', 'cisco', 3, 27,
 'Behavioral questions + mock call',
 'Best culture-to-compensation balance among enterprise companies. RepVue 86.28, culture 3.8/5. Interviewers want you to succeed. Won a RepVue Reppy award. Meraki subsidiary has even higher culture at 4.2/5.',
 'Standard mock cold call',
 ARRAY['How do you stay motivated in a high-volume calling environment?', 'Mock cold call', 'Why networking/collaboration technology?', 'Tell me about a time you overcame rejection'],
 ARRAY['Low energy', 'Not understanding Ciscos product portfolio breadth', 'Not knowing about Meraki and WebEx subsidiaries'],
 ARRAY['Interviewers want you to succeed — the process is supportive', 'Cisco Meraki has an even higher culture rating at 4.2/5', '63% SDR quota attainment is solid', 'Won a RepVue Reppy award — strong employer brand'],
 4.1),

('Dell Technologies', 'dell', 3, 21,
 'AI-based pre-recorded video interview (5 questions) + mock cold call/role play',
 'Uses AI-based video interviews as initial screen — record yourself answering 5 questions with no live interviewer. Training academy is amazing and widely praised.',
 'AI video screen (5 questions) + mock cold call',
 ARRAY['5 pre-recorded video interview questions', 'Mock cold call/role play', 'Why Dell?', 'How do you approach learning new technology?'],
 ARRAY['Poor video recording quality or environment', 'Not being natural on camera for the AI screen', 'Expecting top-tier pay — OTE ~$75K is lowest among enterprise'],
 ARRAY['Prepare your recording environment carefully for the AI video screen', 'Training academy is amazing — best for candidates wanting training and brand', 'Dell caps commission and gives minimal raises upon promotion', 'OTE ~$75K is lowest among enterprise — compensated by training quality'],
 3.5),

('VMware', 'vmware', 3, 27,
 'Business presentation',
 'WARNING: Broadcom acquisition has fundamentally altered VMware. Post-acquisition reviews describe brutal routine layoffs, culture destruction, and mass SDR team reductions. Approach with extreme caution.',
 NULL,
 ARRAY['Business presentation', 'Why virtualization/cloud infrastructure?', 'How would you prospect into an enterprise account?'],
 ARRAY['Not researching the Broadcom acquisition impact', 'Investing time without verifying the SDR org still exists', 'Not asking about current team stability'],
 ARRAY['VERIFY the current state of the SDR org before investing time', 'Pre-acquisition culture was highly praised — post-acquisition reviews say Broadcom sucks the life out of everything', 'Compensation data may be outdated post-acquisition', 'If you proceed, ask directly about team stability and recent changes'],
 2.5),

('Adobe', 'adobe', 4, 28,
 'Pre-recorded video submissions (multiple rounds) + product pitch role play + sales case presentation',
 'Sales Academy (ASA) is the primary entry path: SDR → BDR → ISR → AE. Role play scenario provided ~1 week in advance. Adobe flies candidates in for on-site finals with campus tours.',
 'Product pitch role play with scenario provided 1 week in advance',
 ARRAY['Product pitch role play (scenario given in advance)', 'Pre-recorded video answers (multiple rounds)', 'Why Adobe?', 'How do you approach a consultative sale?'],
 ARRAY['Poor video submissions', 'Not using the full week to prepare the role play scenario', 'Not understanding Adobes enterprise product suite'],
 ARRAY['The role play scenario is provided ~1 week in advance — use every day to prepare', 'Adobe Sales Academy is a structured multi-phase program — mention it shows long-term thinking', 'They fly candidates in for on-site finals with campus tours and meals', 'Industry-leading benefits including parental leave — culture is genuinely strong'],
 4.2),

-- ── High-Growth: Developer Tools & Collaboration ────────────────────────────

('Notion', 'notion', 4, 28,
 'Prioritization interview (unique to Notion)',
 'Highest RepVue score (88.47) and top performer ceiling ($190K-$250K) among high-growth companies. The prioritization interview is unique but poorly explained — ask the recruiter for clarification.',
 NULL,
 ARRAY['Prioritization interview questions', 'Why Notion?', 'How would you approach outbound for a PLG product?', 'Tell me about your STAR stories (repeated 5+ times)'],
 ARRAY['Losing energy when repeating the same story 5+ times', 'Not asking the recruiter to clarify the prioritization interview format', 'Not understanding Notions shift from inbound B2C to outbound B2B'],
 ARRAY['Be prepared to repeat the same story 5+ times with equal energy to different interviewers', 'Ask the recruiter to clarify the prioritization interview format — its unique', 'Notion is shifting from inbound B2C to outbound B2B — hunters have opportunity', 'Top performers earn $190K-$250K — highest ceiling among high-growth'],
 4.4),

('Vercel', 'vercel', 5, 28,
 'Prospecting presentation',
 'SDR role called Vercel Development Representative (VDR). Requires unusually high technical aptitude — passion for web development and Next.js understanding preferred. Some roles require 3+ years experience.',
 NULL,
 ARRAY['Prospecting presentation', 'Why developer tools?', 'What do you know about Next.js?', 'How would you sell to engineering leaders and CTOs?'],
 ARRAY['No technical aptitude or passion for web development', 'Not knowing what Next.js is', 'Expecting a standard SDR role — this requires technical depth'],
 ARRAY['Understand Next.js and Vercels deployment platform at a technical level', 'Some VDR roles require 3+ years experience — unusual for SDR', 'Career outlook and progression are close to none per reviews', 'Product-Market Fit 4.4/5 — strong product to sell'],
 3.3),

('Postman', 'postman', 6, 30,
 'Technical assessment + panel presentation + mock prospecting',
 'Uses Account Development Representative (ADR) title. Recommends reading their The API-First World graphic novel before applying. Interview is heavily technical for an SDR role.',
 'Mock prospecting scenario',
 ARRAY['What is the biggest thing in your sales process holding you back?', 'Technical assessment on APIs and automation', 'Panel presentation', 'Why API-first?'],
 ARRAY['Not understanding APIs and automation workflows', 'Being accused of using AI during the interview — a growing concern', 'Not reading The API-First World graphic novel'],
 ARRAY['Read the The API-First World graphic novel before applying', 'Be prepared for technical questions about APIs, automation, and developer personas', 'One candidate was accused of using AI during interview — be authentic', 'Lead flow reportedly low in some segments — ask about pipeline'],
 3.8),

('GitLab', 'gitlab', 6, 40,
 'CREDIT values alignment (Collaboration, Results, Efficiency, Diversity/Inclusion, Iteration, Transparency) + assignment',
 'Entire interview process publicly documented in GitLabs handbook — most transparent hiring of any company. SDR team sits under Revenue Marketing. Clear path: SDR → BDR (12mo) → Manager/ISR/SMB AE.',
 NULL,
 ARRAY['What is your favorite GitLab CREDIT value and why?', 'Assignment/take-home', 'Why open source?', 'How do you demonstrate Transparency in your work?'],
 ARRAY['Not reading the publicly available handbook before interviewing', 'Not knowing CREDIT values', 'Not understanding open-source business model'],
 ARRAY['The ENTIRE interview process is in their public handbook — read it all', 'Know CREDIT: Collaboration, Results, Efficiency, Diversity/Inclusion, Iteration, Transparency', 'Transparent compensation calculator based on role, level, and location', 'Fully remote. SDR team under Revenue Marketing not Sales'],
 3.8),

('Grafana Labs', 'grafana labs', 5, 28,
 'Take-home data analysis task (~10 hours) + CARR storytelling model (Context, Action, Results, Reflection)',
 'Take-home is extensive — analyzing 180-line datasets and creating infographics (~10 hours). Uses CARR model instead of STAR. Interview experience only 22-28% positive despite high RepVue.',
 NULL,
 ARRAY['Analyze this 180-line dataset and create an infographic', 'Tell me a story using CARR format', 'Why observability?', 'How do you approach data-driven prospecting?'],
 ARRAY['Not allocating 10 hours for the take-home', 'Using STAR format instead of CARR (Context, Action, Results, Reflection)', 'Not creating a polished infographic'],
 ARRAY['Take-home requires ~10 hours — analyzing 180-line datasets and creating infographics', 'Use CARR not STAR: Context, Action, Results, Reflection', 'RepVue 87.60 with culture 4.0 despite low interview satisfaction (22-28%)', 'Interviews lean on cultural fit and natural temperament over technical experience'],
 4.3),

('LaunchDarkly', 'launchdarkly', 5, 22,
 'Mock cold call + presentation + homework assignment',
 'Process can extend to a call with the company president in the final round. SDR org described as extremely knowledgeable with strong mentoring. Buyer persona is engineers.',
 'Mock cold call + presentation',
 ARRAY['What was the biggest accomplishment you have achieved in your life?', 'Mock cold call', 'Presentation', 'Why feature management?'],
 ARRAY['No direct SDR/BDR experience — was a dealbreaker in one report', 'Not understanding that the buyer persona is engineers', 'Not being prepared for a presidential-level final round'],
 ARRAY['Process may include a call with the company president — prepare accordingly', 'SDR org described as extremely knowledgeable with strong mentoring', 'Buyer persona is engineers — learn to speak their language', '~51% quota attainment — moderate'],
 3.6),

('Snyk', 'snyk', 4, 24,
 'Behavioral/cultural interviews + AI usage questions',
 'Relatively lightweight compared to peers — no confirmed mock call or take-home. Emerging question: Tell us about your usage of AI technologies in your work. Pre-IPO at $7.4B valuation.',
 NULL,
 ARRAY['Tell us about your usage of AI technologies in your work', 'How do you demonstrate Care Deeply?', 'Why developer security?', 'How do you approach selling to developers?'],
 ARRAY['Not being able to discuss AI usage — its now a standard question', 'Not knowing Snyks 4 values: One Team, Care Deeply, Customer Centric, Forward Thinking', 'Being ghosted and giving up — recruiter communication is inconsistent'],
 ARRAY['Prepare for the AI usage question — its becoming standard across companies', 'Know 4 values: One Team, Care Deeply, Customer Centric, Forward Thinking', 'Pre-IPO at $7.4B valuation — equity matters', 'Recruiter communication is inconsistent — follow up proactively'],
 3.8),

('Miro', 'miro', 5, 29,
 'Mock discovery call + Miro Mindset assessment (6 characteristics) + STAR behavioral',
 'Best candidate experience among high-growth companies at 63.3% positive. Miro Mindset assesses 6 key characteristics throughout. Mock discovery call is scripted on the interviewers side.',
 'Scripted mock discovery call (interviewer has a script, you dont)',
 ARRAY['What kind of coaching style do you like/prefer?', 'Tell me about a time you received and implemented feedback', 'Mock discovery call', 'Why visual collaboration?'],
 ARRAY['Not being familiar with Miro boards — they may use them in the interview', 'Not having strong feedback implementation stories', 'Not understanding the hybrid in-office model'],
 ARRAY['Get familiar with Miro boards — they may use them during your interview', 'Best candidate experience at 63.3% positive — process is well-run', 'Mock discovery call is scripted on their side — focus on genuine discovery', 'Hybrid model requires in-office presence at hub cities'],
 4.0),

('Airtable', 'airtable', 5, 29,
 'Mock discovery call → written feedback notes → REDO the call incorporating feedback (explicit coachability test)',
 'Most innovative assessment design: after first mock call, they give written feedback notes and make you redo the call to see if you incorporated coaching. Purest test of coachability across all 40 companies.',
 'Discovery call done TWICE: first attempt → written feedback → redo incorporating coaching',
 ARRAY['Describe the cloud as if I was your grandma', 'Mock discovery call (done twice)', 'How do you incorporate feedback?', 'Why low-code/no-code platforms?'],
 ARRAY['Not incorporating feedback in the second call attempt', 'Not improving visibly between attempts', 'Not understanding that the redo IS the real test'],
 ARRAY['The second call is the REAL test — first call just establishes baseline', 'Take detailed notes on their written feedback between attempts', 'Only 30.6% quota attainment is lowest in the guide — ask about it directly', 'BDR reviews are more positive than company-wide: best-in-class comp and weekly training'],
 3.4);
